import numpy as np

GRAV = 9.80665
SURFACE_TENSION = 0.074
WATER_DENSITY = 1025
KINEMATIC_SURFACE_TENSION = SURFACE_TENSION / WATER_DENSITY

# Default Numerical Parameters
RELATIVE_TOLERANCE = 1e-3
MAXIMUM_NUMBER_OF_ITERATIONS = 10
ABSOLUTE_TOLERANCE = np.inf
